from TV_controller_classes import TVController

TV = TVController()
print(TV.N)
print('\nFirst:')
TV.first_channel()
print('\nLast:')
TV.last_channel()
print('\nNext:')
TV.next_channel()
print('\nPrevious:')
TV.previous_channel()
print('\nCurrent:')
TV.current_channel()
print('\nis exist:')
TV.is_exist('BC')
